### ISSUE TITLE
update eslint-plugin-react 7.1 => 7.2

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#100]
リリースノート
https://github.com/yannickcr/eslint-plugin-react/releases

rule追加いくつか

**Comment by kanufy** [comment]
ざっとrule確認

### new rules
- [no-unused-state](https://github.com/yannickcr/eslint-plugin-react/pull/1103) docsがないミスのissueは概出
  - あってよさそうかな
  - warnくらいで    
- [boolean-prop-naming](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md)
  - propの名前でboolean強要
  - オプション設定を正規表現とかでやりだすのもなって感じなのでいらなそう
- [no-typos](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-typos.md)
  - いらなそう...

### add options
- auto fix for [jsx-sort-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md)
  - 特に影響はない
  - 設定も現状のままでよさそう ` 'react/jsx-sort-props': 0,`
- getters and setters groups to [sort-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md)
  - そこまで強い気持ちないしそのままでいいかなとおもっている（getters, settersはdefaultでは指定されてない）
  - もし入れるなら適切な場所はみんなで決めたさがある
- noStrings option to [jsx-no-literals](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-literals.md)
  - 結構強いなーとおもうのでここまでせんでもいいかなという印象
  - 現状のまま（ `'react/jsx-no-literals': 1,` ）で良いんじゃなかろうか
- inverse option for always/never to [jsx-boolean-value](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md)
  - 例外的なのはプロダクト毎に設定すべきだしそのまま( `'react/jsx-boolean-value': [2, 'always'],` )でいいかな

**Comment by kanufy** [comment]
@nekoya こんな感じかなーと思うんですが、どうでしょう？

**Comment by nekoya** [comment]
設定内容全般については、自分もそれでいいかなと思います。

### boolean-prop-naming

>propの名前でboolean強要

日本語でぉkという感じなので、少し補足すると

- booleanの場合だけそんなに強く制約するのはいかがなものか
- サンプルでいくと`canHoge`とか`shouldFoo`とかもエラーになってお節介すぎる
- プロジェクト内で好きにする分には構わないが、ここで採用するものではない

てことで採用しなくてよいと思います。

### no-typos

「これLintの仕事なの？」というのが率直な印象なので、同じく不要かなと思う。

ただ、我々はそもそも`React.Component`をextendsしてクラス宣言せずに、常にstateless componentでやっているので、他の声も聞いてみたい気はする。

@himu62 どう？

**Comment by himu62** [comment]
全体的に良さそうです
理由に関しても同意です〜

**Comment by kanufy** [comment]
OK.

これもさくっとあげてしまおう。
あとはeslint本体だな...
