### ISSUE TITLE
eslint v4.2以降の変更あらためて確認する

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#104]
v4.2までのrule追加は #103 でやるとしてそれ以降みる（v4.1はbug fixなのでリンクはってない）

- https://eslint.org/blog/2017/07/eslint-v4.3.0-released
- https://eslint.org/blog/2017/08/eslint-v4.4.0-released
- https://eslint.org/blog/2017/08/eslint-v4.5.0-released

#99 もあるのでそのへんも確認していこう

**Comment by saneyuki** [comment]
- [ESLint v4.6](https://eslint.org/blog/2017/09/eslint-v4.6.0-released) contains a new rule
   - `function-paren-newline`
   - The `generator-star-spacing` rule is now configurable by function **type.**, Bu I don't think it's valuable change for this project. 
- [ESLint v4.7](https://eslint.org/blog/2017/09/eslint-v4.7.0-released) does  not contain a new rule/option.

**Comment by nekoya** [comment]
## Updates

### ESLint 4.3

- https://eslint.org/blog/2017/07/eslint-v4.3.0-released

I consider these updates may affects our rules.

>Update: support more options in prefer-destructuring (#8796) (Victor Hom)

This rule is disabled, and not provide any guideline for such options.

>Update: add enforceInMethodNames to no-underscore-dangle (fixes #7065) (#7234) (Gabriele Petronella)

We accept dangling underscore under classes, thus this option is not suitable to us.


### ESLint 4.4

refs #99

- https://eslint.org/blog/2017/08/eslint-v4.4.0-released

>Update: Add ImportDeclaration option to indent rule (#8955) (David Irvine)

This options is useful in some cases, certainly, but I don't think it is suitable for default.

Thus I'd like to disable it on this repository.


### ESLint 4.5

- https://eslint.org/blog/2017/08/eslint-v4.5.0-released

This update only provides `ignoredNodes` option for `indent` rule.

I consider it is project specific option, not for default settings.


### ESLint 4.6

- https://eslint.org/blog/2017/09/eslint-v4.6.0-released

>One new rule has been added: function-paren-newline

I think it should be decided by each team, and I don't have any strong opinion to this rule.

So I disable it at least on this base ruleset.


### ESLint 4.7

- https://eslint.org/blog/2017/09/eslint-v4.7.0-released

There are no new rules/options.

As a result, our rules are keep going on ESLint 4.7 straightforward.

**Comment by nekoya** [comment]
## ESLint-plugin-React 7.4

- https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.4.0

>Add jsx-curly-brace-presence rule

This is useful to write more robust code. I prefer to enable it as warning.

**Comment by kanufy** [comment]
### eslint 4.3
> Update: prefer-numeric-literals warns Number.parseInt (fixes #8913) (#8929) (Kevin Partington)

なるほど。
readmeに

>This rule set treats ECMA262 6th (ECMA2015) or later one as Tier 1 state.

ってかいてあるからまあ問題はなさそうですね

### eslint 4.4
> Update: Add ImportDeclaration option to indent rule (#8955) (David Irvine)

これあってもいいかなって気がしたんですがまあ微妙なところといわれるとわかるってかんじ

### eslint 4.5
同意見でし

### eslint 4.6
`function-paren-newline` だけど

>{ "minItems": value } requires linebreaks inside function parentheses if the number of parameters/arguments is at least value. Otherwise, it disallows linebreaks.

このオプションとか設定したくはないなって感じ
状況によりけりだしチームによりけりだしdisableでよさそう

### eslint-plugin-react 7.4
よさそう
