### ISSUE TITLE
Update eslint v4.9

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#109]
latest: https://eslint.org/blog/2017/10/eslint-v4.9.0-released

**new rules**

- [multiline-comment-style](https://eslint.org/docs/rules/multiline-comment-style)
  - いらなそう、コメントのスタイルそんなに縛らんでもええやろ
  - `multiline-comment-style: 0`
- [lines-between-class-members](https://eslint.org/docs/rules/lines-between-class-members)
  - 読みやすそうかなーとは思うからありでもよさそうやけどどうやろ

**Comment by saneyuki** [comment]
>> multiline-comment-style
>
> いらなそう、コメントのスタイルそんなに縛らんでもええやろ

make sense.

> lines-between-class-members

IMO, I'm not sure about it increases the readability dramatically. I don't think there is a great benefit to enable it.

**Comment by kanufy** [comment]
dramaticallyに読みやすくなるとはおもってへんよ〜
あってもいいんじゃないくらいのやつ。
断固改行したくない！ってシーンもなさそうだしなというアレやね

**Comment by saneyuki** [comment]
@kanufy 

> dramaticallyに読みやすくなるとはおもってへんよ〜
あってもいいんじゃないくらいのやつ。
断固改行したくない！ってシーンもなさそうだしなというアレやね

Sure.

What I wanted to say is that: "I think this rule set should detect possibie common errors but this should not touch stylistic problems if its rule is just a preference, there is a rest of discussion, and there is no strong policy. [By these design criteria](https://github.com/voyagegroup/eslint-config-fluct#basic-principles-for-settings), I think we don't have any strong motivations to enable this rule".

I don't have any strong opinion that it's pretty bad to enable it...... 

まあ、スタイルの話はゆるくやればいいんでないかなー

**Comment by kanufy** [comment]
そうね〜
まあ上に書いてくれたのに概ね合意なのでなしでいっかーていう想いです。
あとはガーディアン @himu62 さんのご意見きいてアレしよ

**Comment by himu62** [comment]
2人の意見に概ね合意です。  
あってもなくても良さそうだけど、enableにするなら何を目的にenableにするかというのが欲しいですね。

基本的にはゆるくやればいいと思ってるので、必要ならenableという風にしたい気持ちです。

**Comment by saneyuki** [comment]
@himu62 

> あってもなくても良さそうだけど、enableにするなら何を目的にenableにするかというのが欲しいですね。

https://github.com/voyagegroup/eslint-config-fluct#basic-principles-for-settings
