### ISSUE TITLE
update eslint-plugin-react

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#125]
https://github.com/yannickcr/eslint-plugin-react/releases

**Comment by kanufy** [comment]
### new rules / options
- Add forbid-dom-props rule 
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-dom-props.md
  - DOM Nodesだけ特定propsの禁止ができる
  - いらない
- Add jsx-child-element-spacing rule
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-child-element-spacing.md
  -  JSX内のインライン要素の前後のスペースを強制する （ space消えちゃうから `{' '}` とかで調整してね
  - うーんこれもいらなそう
- Add no-this-in-sfc rule 
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-this-in-sfc.md
  - これあっていいんじゃなかろうか
- Add jsx-sort-default-props rule
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-default-props.md
  - defaultPropsの順番をa->zへ
  - いらなそう
  - 地味にdocsに紹介されてるwarningの例が1つミスってる気がするｗ
- Add message option to boolean-prop-naming
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/boolean-prop-naming.md
  - メッセージを頑張るかは各プロジェクト次第だし元々無効にしてるのを有効にするほどでもない
- Add propWrapperFunctions support for boolean-prop-naming
  - これも特には
- Add beforeClosing option to jsx-tag-spacing
  - 現状

```js
'react/jsx-tag-spacing': [1, {
   'closingSlash': 'never',                                                                                                                                                                                                             
   'beforeSelfClosing': 'allow', // Allow to write more XML-ly
   'afterOpening': 'never',
}],
```
`'beforeClosing': 'never'` 追加していいんじゃないかな

- Add instance-methods and instance-variables to sort-comp
  - https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md
  - うーん `static-method` とかも制約かけてないしそこまでいいかなっておもう。
  - 現状はこれ
```js
'order': [
    'constructor',
    'metadata',
    'rendering',
    'lifecycle',
    'everything-else'
],
```

- Add warning for React.addons.TestUtils in no-deprecated
  - 問題なし
- Add URL to rule documentation to the rules metadata
  - 問題なし

**Comment by saneyuki** [comment]
@kanufy 

Should I need some reviews _immediately_ before opening a pull request for it?
I usually write some comments before you open the pull request, but I'm pretty busy now and my replying would need more time....

**Comment by kanufy** [comment]
Sorry, this issue is my own survey memos for PR.
So, I don't want your comments even immediately for this issue.
Don't worry, I will create PR when have time ,too ;D
