### ISSUE TITLE
Update ESLint v4.18

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#128]
https://eslint.org/blog/2018/02/eslint-v4.18.0-released

### Enhancements
> Update: fix indent bug with binary operators/ignoredNodes 

はい

> Update: add named imports and exports for object-curly-newline 

これも現状無効に設定してあるけど、import/export もケースバイケースなのでとくに有効にするモチベーションはないかなとおもう

> Update: support eslint-disable-* block comments

nrhd

**Comment by saneyuki** [comment]
@kanufy 

I'm also creating a new pull request to fix this. May I open the new pull request? Or are you working it?

**Comment by kanufy** [comment]
お、おねがいしたいですだmm
