### ISSUE TITLE
Add the configuration for eslint-plugin-import

### ISSUE THREAD

**Issue by saneyuki** [voyagegroup/eslint-config-fluct#135]
## Motivaton

[eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) is useful to check a coding style and mistakes for a module including ES Module, commonjs, and amd.

Now, I'm creating a new configuration for it. So I'd like to upstream it for this repository as Tier 1 rule set.

## Pros

* Provide the configuration for eslint-plugin-import.
   * This improves a "battery-included" experience for this repository.
   * This change is opt-in. This does not enforce to use the config for all users who use this project.

## Cons

* Increases a maintain cost.
   * We need to gardening our dependencies. This change would add more packages to it.
* The risk to upgrade ESLint.
   * This kind of plugin might delay to support the latest ESLint. It would be a risk to upgrade our dependencies by daily gardening.

**Comment by saneyuki** [comment]
@nekoya @kanufy How do you think about this proposal?

**Comment by saneyuki** [comment]
> This improves a "battery-included" experience for this repository.

My comment lacks some information.
If a user project mixes `.js` and `.ts`, this plugin would requires an extra-configuration.
We can define such pattern as a document. But it's not a perfect "battery-included" experience.

**Comment by kanufy** [comment]
`eslint-plugin-import` のruleのメンテナンスをしなくてはいけなくなるんだよね
わりとめんどくさいかなーっていうイメージある

それにまさるメリットどんくらいあるっけみたいなのが。
`eslint-plugin-import` どうしてもほしいんだよねってのがts書いてるとないかなあみたいなのがすごく。
（各設定jsファイルとかはあるけど）

ちなみに

>This change is opt-in. This does not enforce to use the config for all users who use this project.

はぜっきーも下にかいてるけど必須かなっておもう。（import/no-unresolvedあたりでTSだとbabelなりなんなりに設定必要みたいなのをちらっとみたので）

**Comment by saneyuki** [comment]
[This configuration](https://github.com/saneyuki/linkplaces/blob/master/tools/eslint/import.js) would be my proposal for this issue.

**Comment by saneyuki** [comment]
@kanufy 

> eslint-plugin-import のruleのメンテナンスをしなくてはいけなくなるんだよね
>  わりとめんどくさいかなーっていうイメージある

I agree that this increases a maintenance burden.
Honestly, I'm not sure about that whether the burden is easy or not.

[By their release note](https://github.com/benmosher/eslint-plugin-import/blob/master/CHANGELOG.md), I seem they would publish a newer version per 1 month. As my impression, it would be similar to eslint-plugin-react's pace.

--------------------------------

> それにまさるメリットどんくらいあるっけみたいなのが。
> eslint-plugin-import どうしてもほしいんだよねってのがts書いてるとないかなあみたいなのがすごく。
> （各設定jsファイルとかはあるけど）

eslint-plugin-import supports es module mainly. But they also supports commonjs by [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) or others.

And if you don't use typescript (like a simple CLI or batch script), then this rule set would be pretty useful.
IMO, this is pretty useful to maintain a import/require in a config file for build system.

--------------------------------

>> This change is opt-in. This does not enforce to use the config for all users who use this project.

I think it would be nice to maintain a document like [`example/ES5_BROWSER.md`](https://github.com/voyagegroup/eslint-config-fluct/blob/master/example/ES5_BROWSER.md).
But we need to pay the maintenance cost for it on major release.

**Comment by kanufy** [comment]
>And if you don't use typescript (like a simple CLI or batch script), then this rule set would be pretty useful.
>IMO, this is pretty useful to maintain a import/require in a config file for build system.

そうっすねー
まあなんで設定用jsファイルにとってはメリットあるけど、対してのメンテナンスコストがどんくらいになるんだっけなあみたいなのがあるかんじかな。
1ヶ月に1回かー、んーまあ...

---

>I think it would be nice to maintain a document like example/ES5_BROWSER.md.
>But we need to pay the maintenance cost for it on major release.

そういうサンプルあると助かりそうね。
まあそのサンプル維持もコストわかるってかんじだ

**Comment by saneyuki** [comment]
After the F2F conversation, I decide to withdraw this proposal.

Thank you!
