### ISSUE TITLE
Set Slack notification

### ISSUE THREAD

**Issue by nekoya** [voyagegroup/eslint-config-fluct#64]
@saneyuki Which channel do you like?

**Comment by saneyuki** [comment]
I'm not sure about the benefit to enable the notification of this for our internal slack. Is it really has benefit?

**Comment by nekoya** [comment]
Slack notification would be efficient publicity tool to VG people. It is a benefit enough to add webhook, I think.

In addition, I'm watching activities of any repository by Slack notification. It is hard to me checking all e-mail notification immediately.

If you don't have any motivation/interest, I'm okay to set a webhook by myself.

**Comment by saneyuki** [comment]
Okay. Let's do this!

**Comment by nekoya** [comment]
I'll send it to #javascript !

**Comment by nekoya** [comment]
Done
