### ISSUE TITLE
Update eslint v4.1.1 > 4.2.0

### ISSUE THREAD

**Issue by kanufy** [voyagegroup/eslint-config-fluct#97]
http://eslint.org/blog/2017/07/eslint-v4.2.0-released
でたのであげようかなーと

### 新しいruleとオプション
- `getter-return`
  - あってよさそう。
  - warnかな
- `no-sync` `{ allowAtRootLevel: } `
  - allowAtRootLevelのdefalutはfalse
  - 現状の ` 'no-sync': 1,` のままでよさそうな。
- `multiline-ternary` `{ always-multiline: }`
  - いらなそう。
  - 現状の `'multiline-ternary': 0, ` でいいんじゃないかな。

**Comment by kanufy** [comment]
eslintあげたらeslint-plugin-reactの `jsx-curly-spacing` が壊れるらしい
https://github.com/yannickcr/eslint-plugin-react/issues/1290

**Comment by nekoya** [comment]
`eslint-plugin-react`は修正されたけど、まだリリースされてない状況っぽい。

試しにeslint 4.2.0を入れてみたら、 https://github.com/eslint/eslint/issues/8908 の問題が確認された。

いずれにしても`eslint-plugin-react`のリリースを待つことになりそう。

**Comment by kanufy** [comment]
哀しいことに4.1=>4.2かと思っていたが
まだ4.0だった。にゃーん。

## 4.0.0 -> 4.1.1
- リリースノート
  - http://eslint.org/blog/2017/06/eslint-v4.1.0-released
  - http://eslint.org/blog/2017/06/eslint-v4.1.1-released

主にこのあたりだろうか
- Add eslintIgnore support to package.json
	- すでに `.eslintIgnore` ファイルあるしいいかなあ
- Add `overrides/files` options for glob-based config
        - 設定ファイルの条件付き上書きとかできるみたい
	- これはなんか便利かもしれないけど各プロジェクト内の話だと思うのでパス
- Add ignoreComments option to [no-trailing-spaces](http://eslint.org/docs/rules/no-trailing-spaces)
	- コメントのあとにも空白あるほうがわかりやすいし現状のまま
	- （ `'no-trailing-spaces': 1,` ）

**Comment by nekoya** [comment]
`getter-return`はESLintの仕事なのかという気もするが（TypeScript使おう）、明示的に何も返したくないシチュエーションもまずないだろうからwarnでよさそう。

他のは、特に取り立てて取り込む必要ないかなということで同意です。
